[project]
name = "pyside6-utils"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyside6>=6.9.0",
    "resource-getters>=1.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
